- name: Install Zabbix
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Install prerequisites
      apt: 
        pkg:
        - apache2
        - wget
        - net-tools
