- name: Install Zabbix
  hosts: all
  tasks:
    - name: Install prerequisites
      apt: pkg={{ item }} state=present update_cache=yes
      with_items:
        - wget
        - net-tools
      debug:
        msg: "Done!"
