- hosts: all
  become: yes
  roles:
     - { role: geerlingguy.apache }
 #    - { role: dj-wasabi.zabbix-server, zabbix_server_database: mysql, zabbix_server_database_long: mysql }
     
     - { role: dj-wasabi.zabbix-server, zabbix_server_database: mysql, zabbix_server_database_long: mysql, zabbix_server_dbport: 3306 }
     - { role: dj-wasabi.zabbix-web, zabbix_url: 192.168.154.150, zabbix_server_database: mysql, zabbix_server_database_long: mysql, zabbix_server_dbport: 3306}
