# Install a role from GitHub  
- name: ansible-zabbix-web
  src: https://github.com/dj-wasabi/ansible-zabbix-web
# Install a role from GitHub  
- name: ansible-zabbix-server
  src: https://github.com/dj-wasabi/ansible-zabbix-server
# Install a role from GitHub
- name: geerlingguy.apache
  src: https://github.com/geerlingguy/ansible-role-apache
